src/main/java/org/springframework/samples/petclinic/repository/EmployeeRepository.java, src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataEmployeeRepository.java, src/main/java/org/springframework/samples/petclinic/service/EmployeeService.java, src/main/java/org/springframework/samples/petclinic/web/EmployeeController.java, src/main/webapp/WEB-INF/jsp/employees/createOrUpdateEmployeeForm.jsp, src/main/webapp/WEB-INF/jsp/employees/employeesDetails.jsp, src/main/webapp/WEB-INF/jsp/employees/findEmployees.jsp
=> Creating and deleting functionality implemented. Now, a director can

src/main/java/org/springframework/samples/petclinic/model/LoanApplication.java, src/test/java/org/springframework/samples/petclinic/model/ValidatorLoanAppTests.java, src/test/java/org/springframework/samples/petclinic/model/ValidatorLoanTests.java, src/test/java/org/springframework/samples/petclinic/service/LoansTest.java
Loan and LoanApp entities tested.
=> Loan and LoanApp TEST

src/main/java/org/springframework/samples/petclinic/model/CreditCard.java, src/main/java/org/springframework/samples/petclinic/model/CreditCardApplication.java, src/test/java/org/springframework/samples/petclinic/model/ValidatorCreditCardAppTests.java, src/test/java/org/springframework/samples/petclinic/model/ValidatorCreditCardTests.java
The tetsing of CreditCard and CreditCardApplication entities.
=> Task0.c create credit cardand credit card application testing

src/main/java/org/springframework/samples/petclinic/service/BankAccountService.java, src/main/java/org/springframework/samples/petclinic/web/BankAccountController.java, src/main/webapp/WEB-INF/jsp/accounts/showAccountInfo.jsp
=> Task2.B finished. Now, a bankAccount can be deleted by the client if it

src/main/java/org/springframework/samples/petclinic/web/BankAccountController.java, src/main/webapp/WEB-INF/jsp/accounts/accounts.jsp, src/main/webapp/WEB-INF/jsp/accounts/depositMoney.jsp
Now customers can make deposits to their bank accounts as long as the amount is not negative
=> Task2.E finished. 

src/test/java/org/springframework/samples/acmerico/model/ValidatorBankAccountTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorClientsTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorCreditCardAppTests.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorCreditCardTests.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorEmployeeTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorInstantTransferTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorTests.java
Corrijo los últimos detalles de los tests
=> Todos los tests corregidos

src/test/java/org/springframework/samples/acmerico/model/ValidatorLoanAppTests.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorLoanTests.java
Test parametrizados de Loan y LoanApplication
=> Parameterized tests

src/main/java/org/springframework/samples/acmerico/repository/ClientRepository.java, src/main/java/org/springframework/samples/acmerico/repository/springdatajpa/SpringDataClientRepository.java, src/main/java/org/springframework/samples/acmerico/service/ClientService.java, src/main/java/org/springframework/samples/acmerico/web/ClientController.java, src/main/webapp/WEB-INF/jsp/clients/clientsDetails.jsp, src/main/webapp/WEB-INF/jsp/clients/createOrUpdateClientForm.jsp, src/main/webapp/WEB-INF/jsp/clients/findClients.jsp, src/test/java/org/springframework/samples/acmerico/service/ClientsTest.java
Tests de servicio de Client completado con todos los métodos disponibles actualmente en el servicio
=> Tests client servicio

src/main/java/org/springframework/samples/acmerico/service/BankAccountService.java, src/main/java/org/springframework/samples/acmerico/service/TransferAppService.java, src/test/java/org/springframework/samples/acmerico/service/BankAccountsTest.java
Tests de servicio de BankAccount completados con todos los métodos implementados actualmente
=> Tests de servicio de BankAccount 

src/main/java/org/springframework/samples/acmerico/service/TransferAppService.java, src/test/java/org/springframework/samples/acmerico/service/TransferApplicationsTest.java
Todos los tests de servicio de TransferApp posibles y bug corregido
=> Tests transfer app servicio

src/main/java/org/springframework/samples/acmerico/apis/controller/ExchangeController.java, src/main/java/org/springframework/samples/acmerico/apis/model/foreignExchange/Container.java, src/main/java/org/springframework/samples/acmerico/model/Client.java, src/main/java/org/springframework/samples/acmerico/model/CreditCardApplication.java, src/main/java/org/springframework/samples/acmerico/validator/ExchangeRateValidator.java, src/test/java/org/springframework/samples/acmerico/api/ExchangeRateTest.java
Corregidos algunos bugs del controlador y a la hora de consumir la API gracias a los tests
=> Test api exchange rate

src/main/java/org/springframework/samples/acmerico/model/BankAccount.java, src/main/java/org/springframework/samples/acmerico/model/Client.java, src/main/java/org/springframework/samples/acmerico/service/TransferAppService.java, src/main/java/org/springframework/samples/acmerico/web/CreditCardController.java, src/main/java/org/springframework/samples/acmerico/web/EmployeeController.java, src/main/java/org/springframework/samples/acmerico/web/TransferAppController.java, src/main/resources/db/hsqldb/data.sql, src/test/java/org/springframework/samples/acmerico/controller/ClientControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/CreditCardControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/EmployeeControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/TransferAppControllerTest.java
Todos los test de los controladores funcionando mas optimizaciones y arreglos de los mismos:
-Optimización de CreditCardController.
-Optimización de TransferAppController y arreglo de datos en el data.sql incoherentes y que hacían fallar la aplicación.
-Optimización de EmployeeController.
=> Testde controlador2

src/test/java/org/springframework/samples/acmerico/web/BankAccountControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/ClientControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/CreditCardApplicationControllerTest.java
Falta el accept y el refuse de credit card application
=> Test de controllers

pom.xml, src/main/webapp/WEB-INF/jsp/users/createClientForm.jsp, src/test/java/org/springframework/samples/acmerico/ui/ClientLoginUITest.java, src/test/java/org/springframework/samples/acmerico/ui/ClientRegisterUITest.java
update pom, caso positivo. Falta automatizar el test para que corra la aplicacion sola
=> Creado caso positivo de creacion de clientes

src/main/java/org/springframework/samples/acmerico/repository/CreditCardRepository.java, src/main/java/org/springframework/samples/acmerico/service/CreditCardAppService.java, src/main/java/org/springframework/samples/acmerico/util/CreditCardNumberGenerator.java
Genera la tarjeta de crédito al aceptar la solicitud un trabajador.
=> CreditCardGenerator

src/main/java/org/springframework/samples/acmerico/repository/CreditCardRepository.java, src/main/java/org/springframework/samples/acmerico/repository/TransferAppRepository.java, src/main/java/org/springframework/samples/acmerico/service/CreditCardAppService.java, src/main/resources/db/hsqldb/data.sql, src/test/java/org/springframework/samples/acmerico/model/ValidatorCreditCardTests.java, src/test/java/org/springframework/samples/acmerico/web/CreditCardControllerTest.java
Cambiados todos los números de tarjeta a tipo VISA.
=> Aceptaryrechazarsolicituddetarjetasdecrédito

src/main/webapp/WEB-INF/jsp/accounts/showAccountInfo.jsp, src/main/webapp/WEB-INF/tags/menu.tag, src/test/java/org/springframework/samples/acmerico/ui/AddRemoveWorkerUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreateCreditCardAppUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreditCardApplicationInformationUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreditCardInformationUITest.java, src/test/java/org/springframework/samples/acmerico/ui/InstantTransferUITest.java, src/test/java/org/springframework/samples/acmerico/ui/LoanCreateUITest.java, src/test/java/org/springframework/samples/acmerico/ui/PersonalInformationClientUITest.java
para que no surjan mas problemas a la hora de seguir implementando con respecto a los UI test
=> Añado id a los botones y corrijo errores de los UI TEST

src/main/java/org/springframework/samples/acmerico/web/CreditCardAppController.java, src/main/java/org/springframework/samples/acmerico/web/LoanApplicationController.java, src/main/java/org/springframework/samples/acmerico/web/TransferAppController.java, src/main/java/org/springframework/samples/acmerico/web/WelcomeController.java, src/test/java/org/springframework/samples/acmerico/service/LoanApplicationsTest.java, src/test/java/org/springframework/samples/acmerico/web/LoanAppControllerTest.java
Test de unitarios de esta implementacion.
=> Loan apps mine listing testing

src/main/resources/db/hsqldb/data.sql, src/main/webapp/WEB-INF/jsp/loans/loanInfo.jsp, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/GrantedLoansStepDefinitions.java, src/test/java/org/springframework/samples/acmerico/service/LoanApplicationsTest.java
Arreglo de un fallo en GrantedLoansStepDefinitions y añadida una tabla a la vista de los prestamos creados por un director, donde se muestran las LoanApplications aceptadas del préstamo que se muestre.
=> Boton loan apps aceptadas de una loan

src/main/java/org/springframework/samples/acmerico/configuration/SecurityConfiguration.java, src/main/java/org/springframework/samples/acmerico/service/LoanService.java, src/main/java/org/springframework/samples/acmerico/web/LoanApplicationController.java, src/main/java/org/springframework/samples/acmerico/web/LoanController.java, src/main/webapp/WEB-INF/jsp/loanApp/loanAppList.jsp, src/main/webapp/WEB-INF/jsp/loans/loanInfo.jsp, src/main/webapp/WEB-INF/jsp/loans/loanList.jsp, src/main/webapp/WEB-INF/jsp/loans/personalicedLoanList.jsp, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/AbstractStep.java, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/ClientsLoansAppInfo.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorDebtTest.java, src/test/java/org/springframework/samples/acmerico/service/LoansTest.java, src/test/java/org/springframework/samples/acmerico/web/LoanAppControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/LoanControllerTest.java
=> Cobrarprestamosycreardeudastesting

src/main/java/org/springframework/samples/acmerico/web/UserController.java, src/main/webapp/WEB-INF/tags/menu.tag, src/test/java/org/springframework/samples/acmerico/ui/AddRemoveWorkerUITest.java, src/test/java/org/springframework/samples/acmerico/ui/ClientListUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreditCardInformationUITest.java
Todos los UI tests disabled arreglados
=> Arreglar tests disabled

src/main/webapp/WEB-INF/tags/menu.tag, src/test/java/org/springframework/samples/acmerico/bdd/ClientDebts.feature, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/AbstractStep.java, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/AcceptRefuseLoanAppsStepDefinitions.java, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/BankAccountInfoStepDefinitions.java, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/ClientsDebtsStepDefinitions.java, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/GrantedLoansStepDefinitions.java
Test de Interfaz de usuario, con el caso negativo y positivo para dicha acción.
=> Accederallistadodeclientescondeudascomoempleado uitestcucumber

src/main/java/org/springframework/samples/acmerico/model/CreditCard.java, src/main/java/org/springframework/samples/acmerico/model/CreditCardApplication.java, src/main/java/org/springframework/samples/acmerico/web/CreditCardController.java, src/test/java/org/springframework/samples/acmerico/e2e/ClientControllerIntegrationTests.java, src/test/java/org/springframework/samples/acmerico/e2e/CreditCardControllerIntegrationTests.java
no permite comprobarlo en MySQL
=> Tests de integracion del controlador de CreditCard. Uno de los métodos

src/main/java/org/springframework/samples/acmerico/model/Client.java, src/main/java/org/springframework/samples/acmerico/model/Debt.java, src/main/java/org/springframework/samples/acmerico/model/LoanApplication.java, src/main/java/org/springframework/samples/acmerico/web/DebtController.java, src/test/java/org/springframework/samples/acmerico/service/DebtsTest.java, src/test/java/org/springframework/samples/acmerico/web/DebtControllerTest.java
Test unitarios de la tarea mencionada en el nombre de la rama
=> Test Unitarios de esta tarea

src/test/java/org/springframework/samples/acmerico/e2e/EmployeeControllerIntegrationTests.java, src/test/java/org/springframework/samples/acmerico/e2e/LoanApplicationControllerIntegrationTests.java
Tests de integración de Loan Application Controller
=> Test intregacion loanapp

src/main/java/org/springframework/samples/acmerico/model/LoanApplication.java, src/main/java/org/springframework/samples/acmerico/service/LoanAppService.java, src/main/java/org/springframework/samples/acmerico/service/LoanService.java, src/main/java/org/springframework/samples/acmerico/web/LoanController.java, src/main/webapp/WEB-INF/jsp/loanApp/loanAppList.jsp, src/main/webapp/WEB-INF/jsp/loans/loanInfo.jsp, src/test/java/org/springframework/samples/acmerico/e2e/CreditCardAppControllerIntegrationTests.java, src/test/java/org/springframework/samples/acmerico/e2e/LoanApplicationControllerIntegrationTests.java, src/test/java/org/springframework/samples/acmerico/web/LoanAppControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/LoanControllerTest.java, src/test/java/org/springframework/samples/acmerico/web/TransferAppControllerTest.java
Arreglo controladores que no hacían nada y funciones incorrectas.
=> Parte de LoanApp arreglada.

src/test/java/org/springframework/samples/acmerico/service/DashboardHSQLTest.java, src/test/java/org/springframework/samples/acmerico/service/mysql/DashboardMYSQLTest.java, src/test/java/org/springframework/samples/acmerico/web/DashboardControllerTest.java
-Test de servicio de dashboard
-Test de controlador de dashboard
=> Unitary test de estadisticas de clientes

src/main/resources/db/mysql/data.sql, src/test/java/org/springframework/samples/acmerico/bdd/stepdefinitions/AbstractStep.java, src/test/java/org/springframework/samples/acmerico/ui/AcceptAndRejectTransferAppUITest.java, src/test/java/org/springframework/samples/acmerico/ui/AddRemoveWorkerUITest.java, src/test/java/org/springframework/samples/acmerico/ui/ClientListUITest.java, src/test/java/org/springframework/samples/acmerico/ui/ClientLoginUITest.java, src/test/java/org/springframework/samples/acmerico/ui/ClientRegisterUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreateCreditCardAppUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreditCardApplicationInformationUITest.java, src/test/java/org/springframework/samples/acmerico/ui/CreditCardInformationUITest.java, src/test/java/org/springframework/samples/acmerico/ui/InstantTransferUITest.java, src/test/java/org/springframework/samples/acmerico/ui/LoanCreateUITest.java, src/test/java/org/springframework/samples/acmerico/ui/PersonalInformationClientUITest.java
Cambio del data.sql de español a inglés y arreglo de la mayoría de los test de interfaz de usuario.
=> Cambiar data.sql ingles

src/main/resources/db/hsqldb/data.sql, src/main/resources/db/mysql/data.sql, src/main/webapp/WEB-INF/jsp/employees/employeesDetails.jsp, src/test/java/org/springframework/samples/acmerico/ui/AddRemoveWorkerUITest.java
Arreglo ultimo ui test y cambio los ultimos datos a ingles
=> Arreglar ui test

src/main/java/org/springframework/samples/acmerico/repository/CreditCardRepository.java, src/main/java/org/springframework/samples/acmerico/repository/springdatajpa/SpringDataCreditCardRepository.java, src/test/java/org/springframework/samples/acmerico/e2e/CreditCardControllerIntegrationTests.java, src/test/java/org/springframework/samples/acmerico/e2e/LoanControllerIntegrationTests.java
=> Arreglo un test para borrar las credit card por un problema en el

src/main/java/org/springframework/samples/acmerico/model/Client.java, src/main/java/org/springframework/samples/acmerico/repository/LoanApplicationRepository.java, src/main/java/org/springframework/samples/acmerico/service/BankAccountService.java, src/main/java/org/springframework/samples/acmerico/service/ClientService.java, src/main/java/org/springframework/samples/acmerico/service/CreditCardAppService.java, src/main/java/org/springframework/samples/acmerico/service/CreditCardService.java, src/main/java/org/springframework/samples/acmerico/service/DebtService.java, src/main/java/org/springframework/samples/acmerico/service/EmployeeService.java, src/main/java/org/springframework/samples/acmerico/service/LoanAppService.java, src/main/java/org/springframework/samples/acmerico/service/LoanService.java, src/main/java/org/springframework/samples/acmerico/service/TransferAppService.java, src/main/java/org/springframework/samples/acmerico/service/UserService.java, src/main/java/org/springframework/samples/acmerico/web/LoanApplicationController.java, src/performance/HU11.scala, src/test/java/org/springframework/samples/acmerico/service/LoanApplicationsHSQLTest.java, src/test/java/org/springframework/samples/acmerico/service/mysql/LoanApplicationsMYSQLTest.java, src/test/java/org/springframework/samples/acmerico/web/LoanAppControllerTest.java
Profiling de la historia de usuario 11.
=> Profiling hu11

src/main/java/org/springframework/samples/acmerico/api/service/ExchangeService.java, src/main/java/org/springframework/samples/acmerico/repository/BankAccountRepository.java, src/main/java/org/springframework/samples/acmerico/repository/ClientRepository.java, src/main/java/org/springframework/samples/acmerico/service/BankAccountService.java, src/main/java/org/springframework/samples/acmerico/service/ClientService.java, src/main/java/org/springframework/samples/acmerico/service/LoanAppService.java, src/main/java/org/springframework/samples/acmerico/util/BankAccountNumberGenerator.java, src/main/java/org/springframework/samples/acmerico/util/ViolationAssertions.java, src/main/java/org/springframework/samples/acmerico/validator/ExchangeRateValidator.java, src/main/java/org/springframework/samples/acmerico/web/BankAccountController.java, src/main/java/org/springframework/samples/acmerico/web/LoanApplicationController.java, src/main/java/org/springframework/samples/acmerico/web/LoanController.java, src/main/webapp/WEB-INF/jsp/accounts/showAccountInfo.jsp, src/test/java/org/springframework/samples/acmerico/e2e/BankAccountControllerIntegrationTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorDebtTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorInstantTransferTest.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorLoanAppTests.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorLoanTests.java, src/test/java/org/springframework/samples/acmerico/model/ValidatorTransferApplicationTest.java, src/test/java/org/springframework/samples/acmerico/service/BankAccountsHSQLTest.java, src/test/java/org/springframework/samples/acmerico/service/mysql/BankAccountsMYSQLTest.java, src/test/java/org/springframework/samples/acmerico/service/mysql/LoanApplicationsMYSQLTest.java, src/test/java/org/springframework/samples/acmerico/ui/AcceptAndRejectTransferAppUITest.java, src/test/java/org/springframework/samples/acmerico/web/BankAccountControllerTest.java
7 bugs y 33 code smells arreglados.
Además, elimino la parte de deleteBankAccount que no funciona por la incompatibilidad de las bases de datos
=> Refactoring maria
